#include<iostream>
using namespace std;
int main(){

/* 2D ARRAY CREATION */

// int arr[2][3] = {
//     {1, 2, 3},
//     {4, 5, 6}
// };


/* ACCESINNG 2D ARRAY */
// cout<<arr[0][0]; // 6
// cout<<arr[0][1]; // 6
// cout<<arr[0][2]; // 6
// cout<<arr[1][0]; // 6
// cout<<arr[1][1]; // 6
// cout<<arr[1][2]; // 6



/* Input & Output of 2D Array */
// int arr[2][3];
// for(int i = 0 ; i < 2 ; i++){
//     for(int j = 0 ; j < 3 ; j++){
//         cin>>arr[i][j];
//     }
    
// }

// for(int i = 0 ; i < 2 ; i++){
//     for(int j = 0 ; j < 3 ; j++){
//         cout<<arr[i][j]<<",";
//     }
//     cout<<endl;
// }

/* Traversl of 2D Array */
/* ROW TRAVERSL */


    return 0;
}